runtime: nodejs20

# instance_class: F1
# service: my-portfolio

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)$
    static_files: build/\1
    upload: build/(.*)
